version: "3.9"

services:
#    web:
#        build: .
#        ports:
#            - "80:8000"
#        depends_on:
#            db:
#                condition: service_healthy
#        command: ["python", "app.py"]

    db:
        image: postgres:15.1-alpine3.17
        restart: always
        env_file: ./.env
        healthcheck:
            test: [“CMD-SHELL”, “pg_isready”]
            interval    : 1s
            timeout: 5s
            retries: 10
    adminer:
        image: adminer:4.8.1-standalone
        restart: always
        ports:
            - 8080:8080