version: "3.9"

services:
    stan:
        image: nats-streaming:0.25.3-alpine3.17
        ports:
            - "4222:4222"
            - "8222:8222"
        depends_on:
            - db
#            db:
#                condition: service_healthy

    db:
        image: postgres:15.1-alpine3.17
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        restart: always
        ports:
            -   "5432:5432"
        env_file: ./.env
#        healthcheck:
#            test: [“CMD-SHELL”, “pg_isready”]
#            interval    : 1s
#            timeout: 5s
#            retries: 10
    adminer:
        image: adminer:4.8.1-standalone
        restart: always
        ports:
            - "8080:8080"