version: "3.9"

services:
    stan:
        image: nats-streaming:0.25.3-alpine3.17
        ports:
            - "4222:4222"
            - "8222:8222"
        depends_on:
            - db

    db:
        image: postgres:15.1-alpine3.17
        volumes:
            - ./pgdata:/var/lib/postgresql/data
            - ./psql:/docker-entrypoint-initdb.d/:ro
        restart: always
        ports:
            -   "5432:5432"
        env_file: service/.env

    adminer:
        image: adminer:4.8.1-standalone
        restart: always
        ports:
            - "8080:8080"