version: "3.9"

services:
    go-stan-http-app:
        build:
            dockerfile: Dockerfile_app
        container_name: app
        hostname: app
        env_file:
            -   .env
        ports:
            -   "8000:8000"
        restart: always
        depends_on:
            - nats-streaming

    nats-streaming:
        image: nats-streaming:0.25.3-alpine3.17
        container_name: stan
        hostname: stan
        ports:
            - "4222:4222"
            - "8222:8222"
        restart: always
        depends_on:
            database:
                condition: service_healthy



    database:
        image: postgres:15.1-alpine3.17
        container_name: postgres
        hostname: db_host
        env_file: .env
        volumes:
            - ./pgdata:/var/lib/postgresql/data
            - ./sql:/docker-entrypoint-initdb.d/:ro
        ports:
            -   "5432:5432"
        healthcheck:
            test: [ "CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB" ]
            interval: 15s
            timeout: 20s
            retries: 10
            start_period: 90s
        restart: always

    util:
        image: adminer:4.8.1-standalone
        container_name: adminer
        hostname: adminer
        env_file: .env
        ports:
            - "8080:8080"
        restart: always
        depends_on:
            - database